---
dist: trusty
addons:
  apt:
    packages:
    - libjansson-dev
    - libjansson4
    - autoconf-archive
    - autotools-dev
    - automake
    - autoconf
language: cpp
script: ./buildconf.sh && ./configure && make && make check
